### ISSUE TITLE
[Bug]: Cannot display the cover image uploaded by Itunes

### ISSUE THREAD

**Issue by iamyx123** [ciderapp/Cider#1629] opened 2023-01-09 02:57 UTC
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

windows11 22H2

### Where did you download Cider from?

GitHub

### Describe the Bug

Cannot display the cover image uploaded by Itunes.

### Steps to Reproduce

1.Upload a song by Itunes.
2.Play it in Cider.

### Anything else?

<img width="670" alt="2023-01-09_105126" src="https://user-images.githubusercontent.com/88130457/211234192-0ed49c70-9d39-42ff-981b-4adf3bb208b3.png">

<img width="666" alt="2023-01-09_105220" src="https://user-images.githubusercontent.com/88130457/211234195-64c5db7a-4fc7-42a3-9886-277cb24f066d.png">

**Comment by coredev-uk** [comment] 2023-01-12 13:08
Duplicate of #1612

**Closed by coredev-uk** 2023-01-12 13:08 UTC
Labels: bug, duplicate, renderer
