### ISSUE TITLE
[Bug]: Apple Music Radio leads to unusability

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider#689] opened 2022-03-24 14:20 UTC
### Describe the Bug

Selecting a radio station(Apple Music 1) leads to unusability of Cider. The app can no longer be used, no buttons are working anymore.

### Steps to Reproduce

1. Play Apple Music 1 Radio
2. (Click on it's cover in the playbar for fullscreen)

### Environment Information

- OS: Windows 10 Build 21H2
- App Version: 1.3.0-alpha.1516

### Anything else?

vue.js:6 RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Cn.convertTime (vueapp.js:1437)
    at Cn.eval (eval at Qa (vue.js:1), <anonymous>:4:500)
    at Cn.e._render (vue.js:6)
    at Cn.r (vue.js:6)
    at pn.get (vue.js:6)
    at pn.run (vue.js:6)
    at ln (vue.js:6)
    at Array.<anonymous> (vue.js:6)
    at We (vue.js:6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vringster** [comment] 2022-03-24 15:04
When you click on a song after playing the Radio, everything starts to work, correct?

**Comment by UnbreakCode** [comment] 2022-03-24 17:06
> When you click on a song after playing the Radio, everything starts to work, correct?

yes

**Comment by SkyRexHUN** [comment] 2022-04-07 11:03
Pressing play on any other radio show or radio station kills Cider as well. (J-pop Now radio or asia DREAM radio for example).

**Comment by SkyRexHUN** [comment] 2022-05-22 17:11
Any updates? (Commented to remove stale)

**Comment by yazninja** [comment] 2022-05-23 00:45
> Any updates? (Commented to remove stale)

Hey i think the issue is fixed in latest releases, check in the discord server (`/branchbuilds`) or [releases repo](https://github.com/ciderapp/cider-releases/releases) for an updated Cider build. I can listen to Apple music 1 while navigating thru the app

**Comment by SkyRexHUN** [comment] 2022-05-23 08:22
I don't listen to just "Apple Music 1" specifically, sure that one station works, but there are other stations like Asia Dream radio and even radio shows like J-pop Now Radio that cannot be played in the current version.

**Comment by yazninja** [comment] 2022-05-23 08:48
> I don't listen to just "Apple Music 1" specifically, sure that one station works, but there are other stations like Asia Dream radio and even radio shows like J-pop Now Radio that cannot be played in the current version.

yeah, those stations are episodic stations, they aren't streamed live. They can't be played with Cider nor the AM website. both use the same underlying technology. MusicKit, and it does not currently support episodic stations. You would need iTunes for these

**Comment by SkyRexHUN** [comment] 2022-05-23 09:04
You're right on the episodic stations, but Asia Dream Radio is a proper live radio station, it isn't episodic, still it can't be played sadly. Any chance these will be playable in Cider?

**Comment by yazninja** [comment] 2022-05-23 09:07
> You're right on the episodic stations, but Asia Dream Radio is a proper live radio station, it isn't episodic, still it can't be played sadly. Any chance these will be playable in Cider?

may i ask if this is a third party radio station?

**Comment by SkyRexHUN** [comment] 2022-05-23 09:46
I hope so.

**Comment by UnbreakCode** [comment] 2022-05-23 09:56
I will close the ticket now, since it was fixed a long time ago.

**Closed** 2022-05-23 09:59 UTC
Labels: bug, renderer

**Comment by yazninja** [comment] 2022-05-23 17:10
> I hope so.

hey, new build has the 3rd party live radio stations enabled

**Comment by UnbreakCode** [comment] 2022-05-24 11:11
> hey, [new build](https://github.com/ciderapp/cider-releases/releases/tag/v1.4.7-beta.189) has the 3rd party live radio stations enabled

well seems like not every radio station works...

for example: "80s80s Radio" didn't work

**Comment by yazninja** [comment] 2022-05-25 01:16
> for example: "80s80s Radio" didn't work
Works as of this [release](https://github.com/ciderapp/cider-releases/releases/tag/v1.4.7-beta.222)
