### ISSUE TITLE
[Bug]: Can't skip track forward or backward

### ISSUE THREAD

**Issue by theyanniss23002** [ciderapp/Cider#1408] opened 2022-09-02 09:18 UTC
### Describe the Bug

Can't change track or go back with F7 and F9 keys on keyboard

### Steps to Reproduce

Go to the application and press the F7 or F9 key

### Environment Information

- OS: Monterey 12.5.1 / M1 Pro
- App Version and/or Commit ID: v.1.5.7-beta.8

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment] 2022-09-16 17:18
Duplicate of #1352

**Closed by coredev-uk** 2022-09-16 17:18 UTC
Labels: duplicate
