### ISSUE TITLE
[Bug]: Removing songs from queue always removes the first item, no matter where you click

### ISSUE THREAD

**Issue by DysphoricUnicorn** [ciderapp/Cider#1375] opened 2022-08-19 11:11 UTC
### Describe the Bug

Every time I try to remove a song from my queue, it will remove the first item within the queue, even if that is not the one I clicked on.

### Steps to Reproduce

1. Start an artist's radio station
    - Alternatively play a playlist
2. Try to remove a song that is not the first one from the queue
   - The first song will be removed while the one you clicked on will stay in the queue

### Environment Information

- OS: Arch Linux
- App Version: 1.5.4-beta.51

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by nate-thegrate** [comment] 2022-09-20 17:36
Looks to be a duplicate of #1194.

**Comment by nate-thegrate** [comment] 2022-09-20 17:38
Looks to be a duplicate of #1194.

**Comment by cryptofyre** [comment] 2022-09-20 18:14
Closing due to duplicate

**Closed** 2022-09-24 22:10 UTC
Labels: bug, renderer
