### ISSUE TITLE
[Bug]: [Microsoft Store] Cider is not opening at all. Task Manager shows multiple instances. 

### ISSUE THREAD

**Issue by TheCaptRay** [ciderapp/Cider#941] opened 2022-04-26 15:53 UTC
### Describe the Bug

[Microsoft Store] Cider is not opening at all. Task Manager shows multiple instances. 
No matter what I do, it doesn't open. Previous versions I downloaded .exe from Github worked just fine. 

I bought it on Microsoft, and uninstalled the previous version. Now it doesn't open

### Steps to Reproduce

1. Click Open in Start Menu
2. Doesn't Open

### Environment Information

- OS: Windows 11 
- App Version and/or Commit ID: Latest Windows Store version 1.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment] 2022-04-26 15:56
#927

**Comment by KillerParticles** [comment] 2022-04-26 15:56
Duplicate of #927 

In short, its a known bug and a fix is being rolled out to the MS Store within the next 24 to 48 hours hopefully.

**Closed by vapormusic** 2022-04-26 15:56 UTC
Labels: bug, triage

**Comment by Amaru8** [comment] 2022-04-26 15:57
Hi! We are actively working on fixing the Microsoft Store builds and pushing out a fix as soon as possible.
