### ISSUE TITLE
Problem connecting[Bug]: 

### ISSUE THREAD

**Issue by Russ22gz** [ciderapp/Cider#1596] opened 2022-12-08 17:41 UTC
### Describe the Bug

A bug happened! Each time i try to access my library after signing in on cider a little message pops up saying "Problem Connecting
There may be a network issue.". I have tried multiple times still the same outcome.

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: Windows 11 insider preview beta build
- Desktop Environment: 
- App Version: v1.6.0
- Commit ID:

### How did you download the software?

GitHub

### Code of Conduct

- [x] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment] 2022-12-08 17:52
Duplicate of #1594

**Closed by coredev-uk** 2022-12-08 17:52 UTC
Labels: bug, needs-triage
