### ISSUE TITLE
[BUG] Queue erases the next songs automatically or restarts the Playlist/Artist/Album over again

### ISSUE THREAD

**Issue by camooflage** [ciderapp/Cider#206] opened 2022-01-24 23:44 UTC
**Describe the bug**
When I play a song in the Playlist/Artist/Album, the Queue either gets all erased or makes me start the Playlist/Artist/Album over from the beginning. It does not follow through all the next songs that are supposed to be played in the Playlist/Artist/Album.

**To Reproduce**
1. Go to 'Playlist', or 'Album', or 'Artist'.
2. Reproduce one of the 'songs' in the mid/end of Playlist/Artist/Album.
3. The Queue that appears are either the first songs of the Playlist/Artist/Album aforementioned, or it completely erases the next songs.
4. The next songs are not the ones expected, as they don't follow the playlist sequence. Or when the queue is all erased, the reproduction is stopped after first song that I had decided to listen.

**Expected behavior**
Select a song. Play it. Next song that is played is the sequent one of the list.

**Screenshots**
![First songs in the Playlist](https://user-images.githubusercontent.com/98362876/150883555-38c30b96-2cbd-43b2-8fd0-7df7d6200085.png)
![Queue is all erased](https://user-images.githubusercontent.com/98362876/150883570-3be4f060-d2ba-477c-9f39-aa5d5530a6b6.png)

**Environment Information**
 - OS *Windows 11*: 
 - Application Version *Version 21H2. OS Build 22000.434*: 
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?** No
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

**Comment by gms10ur** [comment] 2022-01-25 00:00
fixed in upcoming @quacksire @vapormusic @cryptofyre and kinda dupe of #156

**Closed** 2022-01-28 08:14 UTC
Labels: bug
