### ISSUE TITLE
[Bug]: Doesn't react to keyboard play, next etc. keys

### ISSUE THREAD

**Issue by MrLutik** [ciderapp/Cider#1429] opened 2022-09-13 20:50 UTC
### Describe the Bug

Doesn't respond to Play/Pause, Next, Previous keys from keyboard

### Steps to Reproduce

Keyboard Logitech G915.

### Environment Information

- OS: Arch Linux Kernel: 5.19.7-arch1-1
- App Version and/or Commit ID: 1.5.6  3b46a623cd48be3a0f62cf94ef25165fc8a3c01a

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment] 2022-09-13 21:13
Whats your Desktop Environment?

**Comment by MrLutik** [comment] 2022-09-13 21:20
> Whats your Desktop Environment?

GNOME 42.4

**Comment by zurahk** [comment] 2022-09-14 02:10
Ditto problems just started today for me, Windows 11, 
Keyboard: Asus ROG STRIX NX TKL MOONLIGHT

**Comment by Tokthree** [comment] 2022-09-14 21:35
I previously fixed my media keys not working by running the application as an admin.

**Comment by coredev-uk** [comment] 2022-09-15 00:34
Duplicate of #1352

**Closed by coredev-uk** 2022-09-15 00:34 UTC
Labels: duplicate
