### ISSUE TITLE
[Bug]: Playing a song with shuffle disabled and then enabling shuffle mid-song will only shuffle the songs after that song in the playlist

### ISSUE THREAD

**Issue by Aria-NL** [ciderapp/Cider#1277] opened 2022-07-13 10:45 UTC
### Describe the Bug

Should be pretty self-explanatory. If you play a song near the end of a playlist (or anywhere in the playlist for that matter) with shuffle toggled off, and then toggle shuffle on during playback, Cider will only shuffle the rest of the songs in the playlist below the current song, i.e. what's in the queue already.

### Steps to Reproduce

1. Ensure shuffle is disabled
2. Begin playback of a song, ideally near the bottom of a playlist to make the effect more visible
3. Enable shuffle
4. View the queue

### Environment Information

- OS: Windows 11 64bit
- App Version and/or Commit ID: 1.5.1-beta.401

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment] 2022-07-22 05:06
Duplicate of #1206

**Closed by coredev-uk** 2022-07-22 05:06 UTC
Labels: bug, duplicate, renderer
